# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-13 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arya', '0002_auto_20170911_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='arya.Permission', verbose_name='拥有权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='arya.Role', verbose_name='拥有角色'),
        ),
    ]
